import { expect, test } from "@playwright/test";

test("native composition, line breaks and keyboard history preserve repeated control identities", async ({ page, context }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/prototype.html");
  await page.getByRole("button", { name: "English", exact: true }).click();
  const editor = page.getByRole("textbox", { name: "Editable document", exact: true });
  const controls = page.locator(".document-field");
  const ids = await controls.evaluateAll(nodes => nodes.map(node => node.getAttribute("data-field-id")));
  const clients = page.getByRole("textbox", { name: "Field value: ПІБ клієнта", exact: true });
  const original = await clients.first().inputValue();
  await page.getByRole("button", { name: "Go to field: ПІБ клієнта", exact: true }).last().click();
  await expect(editor).toBeFocused();
  const cdp = await context.newCDPSession(page);
  await cdp.send("Input.imeSetComposition", { text: "Ї", selectionStart: 1, selectionEnd: 1 });
  await expect(page.getByRole("button", { name: "Export DOCX", exact: true })).toBeDisabled();
  await cdp.send("Input.imeSetComposition", { text: "Їжак Ґанна", selectionStart: 10, selectionEnd: 10 });
  const composed = "Їжак Ґанна 🙂";
  await cdp.send("Input.insertText", { text: composed });
  await expect(clients.first()).toHaveValue(composed);
  await expect(clients.last()).toHaveValue(composed);
  await expect(editor).toBeFocused();
  await page.keyboard.press("Control+z");
  await expect(clients.first()).toHaveValue(original);
  await expect(clients.last()).toHaveValue(original);
  await page.keyboard.press("Control+Shift+z");
  await expect(clients.first()).toHaveValue(composed);
  await expect(clients.last()).toHaveValue(composed);

  await page.keyboard.press("End");
  await page.keyboard.press("Enter");
  await expect(clients.last()).toHaveValue(`${composed}\n`);
  await page.keyboard.insertText("Єва");
  await expect(clients.last()).toHaveValue(`${composed}\nЄва`);
  await page.keyboard.press("Shift+Enter");
  await expect(clients.last()).toHaveValue(`${composed}\nЄва\n`);
  await page.keyboard.insertText("Ілля");
  const multiline = `${composed}\nЄва\nІлля`;
  await expect(clients.first()).toHaveValue(multiline);
  await expect(clients.last()).toHaveValue(multiline);
  expect(await controls.evaluateAll(nodes => nodes.map(node => node.getAttribute("data-field-id")))).toEqual(ids);

  await page.getByRole("button", { name: "Previous field", exact: true }).focus();
  await page.keyboard.press("Enter");
  await expect(editor).toBeFocused();
  expect(await page.evaluate(() => window.getSelection()?.anchorNode?.parentElement?.closest(".document-field")?.getAttribute("data-field-id"))).toBe(ids[3]);
  await page.getByRole("button", { name: "Next field", exact: true }).focus();
  await page.keyboard.press("Enter");
  await expect(editor).toBeFocused();
  expect(await page.evaluate(() => window.getSelection()?.anchorNode?.parentElement?.closest(".document-field")?.getAttribute("data-field-id"))).toBe(ids[4]);
  await page.keyboard.press("ArrowRight");
  await expect.poll(() => page.evaluate(() => window.getSelection()?.isCollapsed)).toBe(true);
  await page.keyboard.press("Backspace");
  await expect(clients.first()).toHaveValue(multiline.slice(0, -1));
  await expect(clients.last()).toHaveValue(multiline.slice(0, -1));
  await page.keyboard.press("Control+z");
  await expect(clients.first()).toHaveValue(multiline);
  await expect(clients.last()).toHaveValue(multiline);
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export DOCX", exact: true }).click();
  await (await download).saveAs("/tmp/fillable-dev-results/keyboard-composition.docx");
  await page.getByRole("button", { name: "Reopen exported DOCX", exact: true }).click();
  await expect(clients.first()).toHaveValue(multiline);
  await expect(clients.last()).toHaveValue(multiline);
  await expect(controls).toHaveCount(5);
  expect(errors).toEqual([]);
  await cdp.detach();
});

test("cancelled and unchanged-final composition preserve fields without duplicate candidates", async ({ page, context }) => {
  await page.goto("/prototype.html");
  const clients = page.getByRole("textbox", { name: "Значення поля: ПІБ клієнта", exact: true });
  const original = await clients.first().inputValue();
  const controls = page.locator(".document-field");
  const ids = await controls.evaluateAll(nodes => nodes.map(node => node.getAttribute("data-field-id")));
  await page.getByRole("button", { name: "Перейти до поля: ПІБ клієнта", exact: true }).last().click();
  await page.keyboard.press("ArrowRight");
  await expect.poll(() => page.evaluate(() => window.getSelection()?.isCollapsed)).toBe(true);
  const cdp = await context.newCDPSession(page);
  await cdp.send("Input.imeSetComposition", { text: "Є", selectionStart: 1, selectionEnd: 1 });
  await cdp.send("Input.imeSetComposition", { text: "", selectionStart: 0, selectionEnd: 0 });
  await expect(clients.first()).toHaveValue(original);
  await expect(clients.last()).toHaveValue(original);
  await expect(clients).toHaveCount(2);
  expect(await controls.evaluateAll(nodes => nodes.map(node => node.getAttribute("data-field-id")))).toEqual(ids);
  await page.getByRole("button", { name: "Перейти до поля: ПІБ клієнта", exact: true }).last().click();
  const value = "Єва Їжак";
  await cdp.send("Input.imeSetComposition", { text: value, selectionStart: value.length, selectionEnd: value.length });
  await cdp.send("Input.insertText", { text: value });
  await expect(clients.first()).toHaveValue(value);
  await expect(clients.last()).toHaveValue(value);
  expect(await controls.evaluateAll(nodes => nodes.map(node => node.getAttribute("data-field-id")))).toEqual(ids);
  await page.keyboard.press("Control+z");
  await expect(clients.first()).toHaveValue(original);
  await expect(clients.last()).toHaveValue(original);
  await page.keyboard.press("Control+Shift+z");
  await expect(clients.first()).toHaveValue(value);
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "Експортувати DOCX", exact: true }).click();
  await (await download).saveAs("/tmp/fillable-dev-results/fast-composition.docx");
  await page.getByRole("button", { name: "Відкрити експортований DOCX", exact: true }).click();
  await expect(clients).toHaveCount(2);
  await expect(clients.first()).toHaveValue(value);
  await expect(clients.last()).toHaveValue(value);
  await expect(controls).toHaveCount(5);
  await cdp.detach();
});
