import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";
import { manualSaving } from "./autosave-setting";
import { openUploadPanel } from "./navigation";

test("saved previews populate on first render, persist, and follow saved fill-mode edits", async ({ page }, info) => {
  const title = `Превʼю Ґанни ${info.project.name}`;
  await page.goto("/");
  await page.getByLabel("Логін", { exact: true }).fill("pagebreaks@example.test");
  await page.getByLabel("Пароль", { exact: true }).fill("Synthetic-browser-Їжак-2026");
  await page.getByRole("button", { name: "Увійти", exact: true }).click();
  await openUploadPanel(page);
  await page.getByLabel("Файл DOCX", { exact: true }).setInputFiles({ name: "preview.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", buffer: await readFile("/fixtures/upload.docx") });
  await page.getByLabel("Назва документа", { exact: true }).fill(title);
  await page.getByRole("button", { name: "Завантажити та зберегти", exact: true }).click();
  let card = page.getByRole("article", { name: title, exact: true });
  await expect(card.locator(".library-preview-placeholder")).toBeVisible();
  await card.getByRole("link", { name: title, exact: true }).click();
  await expect(page.getByText("Редагування дозволено.", { exact: true })).toBeVisible();
  await manualSaving(page);
  await page.getByRole("button", { name: "Заповнення", exact: true }).click();
  const input = page.locator(".fill-form").getByRole("textbox", { name: "Значення поля: ПІБ клієнта", exact: true }).first();
  await input.fill("Єва Ґалаган — превʼю");
  await expect(page.locator(".fill-preview")).toContainText("Єва Ґалаган — превʼю");
  await expect(page.locator(".fill-preview .ProseMirror")).toHaveAttribute("contenteditable", "false");
  const fits = await page.locator(".fill-preview-viewport").evaluate(viewport => {
    const paper = viewport.querySelector('section[data-part="word/document.xml"]')!;
    return paper.getBoundingClientRect().width <= viewport.getBoundingClientRect().width + 1;
  });
  expect(fits).toBe(true);
  await page.getByRole("button", { name: "Зберегти документ", exact: true }).click();
  await expect(page.getByText("Усі зміни документа збережено.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Назад до бібліотеки", exact: true }).click();
  await expect(card.locator(".library-preview-content")).toContainText("Єва Ґалаган — превʼю");
  await page.reload();
  card = page.getByRole("article", { name: title, exact: true });
  await expect(card.locator(".library-preview-content")).toContainText("Єва Ґалаган — превʼю");
  await expect(card.locator(".library-preview")).toHaveAttribute("inert", "");
  await page.screenshot({ path: info.outputPath("saved-gallery-preview.png"), fullPage: true });
});
