import { readFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { expect, test } from "@playwright/test";

test("library uploads both kinds, retries safely, and keeps drafts across a language change", async ({ page }, testInfo) => {
  const bytes = await readFile("/fixtures/upload.docx");
  const file = { name: "Заява-Їжак.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", buffer: bytes };
  const templateTitle = `Шаблон Ґанни — ${testInfo.project.name}`;
  const documentTitle = `Окрема заява Їжака — ${testInfo.project.name}`;
  await page.goto("/");
  await page.getByLabel("Електронна пошта", { exact: true }).fill("library@example.test");
  await page.getByLabel("Пароль", { exact: true }).fill("Synthetic-browser-Їжак-2026");
  await page.getByRole("button", { name: "Увійти", exact: true }).click();
  await expect(page).toHaveURL(/\/documents$/);
  await expect(page.getByRole("heading", { name: "Бібліотека документів" })).toBeVisible();
  let pollFailure = true;
  await page.route("**/api/documents/*/processing", async route => {
    if (pollFailure) { pollFailure = false; await route.abort(); return; }
    await route.continue();
  });
  let fail = true;
  const keys: string[] = [];
  await page.route("**/api/documents", async route => {
    if (route.request().method() === "POST") {
      keys.push(route.request().headers()["idempotency-key"]);
      if (fail) { fail = false; await route.abort(); return; }
    }
    await route.continue();
  });
  await page.getByLabel("Файл DOCX", { exact: true }).setInputFiles(file);
  await page.getByLabel("Назва документа", { exact: true }).fill(templateTitle);
  await page.getByRole("button", { name: "Завантажити та зберегти", exact: true }).click();
  await expect(page.getByRole("alert")).toBeVisible();
  await expect(page.getByLabel("Назва документа", { exact: true })).toHaveValue(templateTitle);
  await page.getByRole("button", { name: "Завантажити та зберегти", exact: true }).click();
  await expect(page.getByRole("article", { name: templateTitle })).toBeVisible();
  const templateCard = page.getByRole("article", { name: templateTitle });
  await expect(templateCard.getByRole("alert")).toBeVisible();
  await templateCard.getByRole("button", { name: "Повторити запит стану", exact: true }).click();
  await expect(templateCard.getByText("Перевірку завершено", { exact: true })).toBeVisible({ timeout: 30000 });
  const templateDownload = page.waitForEvent("download");
  await page.getByRole("article", { name: templateTitle }).getByRole("button", { name: "Завантажити збережений DOCX" }).click();
  const templateFile = await templateDownload;
  expect(templateFile.suggestedFilename()).toBe(file.name);
  expect(await readFile((await templateFile.path())!)).toEqual(bytes);
  expect(keys[0]).toBe(keys[1]);
  await expect(page.getByLabel("Файл DOCX", { exact: true })).toHaveValue("");
  await page.screenshot({ path: testInfo.outputPath("library-uk.png"), fullPage: true });
  await page.getByRole("article", { name: templateTitle }).getByRole("link", { name: "Відкрити", exact: true }).click();
  await expect(page).toHaveURL(/\/editor\/[0-9a-f-]+$/);
  await expect(page.getByRole("textbox", { name: "Редагований документ", exact: true })).toBeVisible();
  const draft = `Незбережений Їжак ${testInfo.project.name}`;
  await page.getByRole("textbox", { name: /^Значення поля:/ }).first().fill(draft);
  await expect(page.getByRole("textbox", { name: "Редагований документ", exact: true })).toContainText(draft);
  await page.screenshot({ path: testInfo.outputPath("workspace-uk.png"), fullPage: true });
  await page.getByRole("link", { name: "Бібліотека документів", exact: true }).click();

  await page.getByLabel("Файл DOCX", { exact: true }).setInputFiles(file);
  await page.getByLabel("Назва документа", { exact: true }).fill(documentTitle);
  await page.getByRole("combobox", { name: "Зберегти як", exact: true }).selectOption("document");
  await page.getByRole("link", { name: "Профіль", exact: true }).click();
  await page.getByRole("combobox", { name: "Мова інтерфейсу" }).selectOption("en");
  await page.getByRole("button", { name: "Зберегти мову" }).click();
  await expect(page.getByText("Your language preference has been saved.", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Document workspace", exact: true }).click();
  const editor = page.getByRole("textbox", { name: "Editable document", exact: true });
  await expect(editor).toContainText(draft);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(editor).not.toContainText(draft);
  await page.getByRole("button", { name: "Redo", exact: true }).click();
  await expect(editor).toContainText(draft);
  await page.screenshot({ path: testInfo.outputPath("workspace-en.png"), fullPage: true });
  await page.getByRole("link", { name: "Document library", exact: true }).click();
  await expect(page.getByLabel("Document title", { exact: true })).toHaveValue(documentTitle);
  await expect(page.getByRole("combobox", { name: "Save as", exact: true })).toHaveValue("document");
  await page.getByRole("button", { name: "Upload and save", exact: true }).click();
  await expect(page.getByRole("article", { name: documentTitle })).toBeVisible();
  const documentDownload = page.waitForEvent("download");
  await page.getByRole("article", { name: documentTitle }).getByRole("button", { name: "Download saved DOCX" }).click();
  expect(await readFile((await (await documentDownload).path())!)).toEqual(bytes);
  page.once("dialog", dialog => dialog.dismiss());
  await page.getByRole("article", { name: documentTitle }).getByRole("link", { name: "Open", exact: true }).click();
  await expect(page).toHaveURL(/\/documents$/);
  page.once("dialog", dialog => dialog.accept());
  await page.getByRole("article", { name: documentTitle }).getByRole("link", { name: "Open", exact: true }).click();
  await expect(page.getByRole("heading", { name: documentTitle, exact: true })).toBeVisible();
  await expect(page.getByRole("region", { name: documentTitle, exact: true }).getByText("Individual document", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Document library", exact: true }).click();
  expect(keys[2]).not.toBe(keys[1]);
  await expect(page.getByRole("tab", { name: "Documents", exact: true })).toHaveAttribute("aria-selected", "true");
  await page.screenshot({ path: testInfo.outputPath("library-en.png"), fullPage: true });
  await page.reload();
  await page.getByRole("tab", { name: "Documents", exact: true }).click();
  await expect(page.getByRole("article", { name: documentTitle })).toBeVisible();
  await expect(page.getByRole("article", { name: documentTitle }).getByText("Inspection complete", { exact: true })).toBeVisible({ timeout: 30000 });
  const list = await (await page.request.get("/api/documents?kind=document")).json();
  const saved = list.items.find((item: { title: string }) => item.title === documentTitle);
  expect(saved.digest).toBe(createHash("sha256").update(bytes).digest("hex"));
  expect(saved.size_bytes).toBe(bytes.length);
  expect(saved.processing_status).toBe("succeeded");
  const beforeDelete = await (await page.request.get("/api/storage/usage")).json();
  const card = page.getByRole("article", { name: documentTitle });
  await card.getByRole("button", { name: "Delete", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await expect(page.getByRole("button", { name: "Cancel", exact: true })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(card.getByRole("button", { name: "Delete", exact: true })).toBeFocused();
  await card.getByRole("button", { name: "Delete", exact: true }).click();
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  expect((await page.request.get(`/api/documents/${saved.id}/download`)).ok()).toBeTruthy();
  await card.getByRole("button", { name: "Delete", exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath("delete-confirmation-en.png"), fullPage: true });
  await page.getByRole("button", { name: "Delete permanently", exact: true }).click();
  await expect(card).toHaveCount(0);
  expect((await page.request.get(`/api/documents/${saved.id}/download`)).status()).toBe(404);
  const afterDelete = await (await page.request.get("/api/storage/usage")).json();
  expect(afterDelete.used_bytes).toBe(beforeDelete.used_bytes - bytes.length);
  await page.reload();
  await page.getByRole("tab", { name: "Documents", exact: true }).click();
  await expect(card).toHaveCount(0);
  await page.getByRole("link", { name: "Profile", exact: true }).click();
  await page.getByRole("combobox", { name: "Interface language" }).selectOption("uk");
  await page.getByRole("button", { name: "Save language" }).click();
  await expect(page.getByText("Мову інтерфейсу збережено.", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Бібліотека документів", exact: true }).click();
  await page.getByRole("tab", { name: "Шаблони", exact: true }).click();

  const copyTitle = `Незалежний документ — ${testInfo.project.name}`;
  let lostCopy = true;
  const copyKeys: string[] = [];
  await page.route("**/api/documents/*/copies", async route => {
    copyKeys.push(route.request().headers()["idempotency-key"]);
    if (lostCopy) {
      lostCopy = false;
      const committed = await route.fetch(); expect(committed.status()).toBe(201);
      await route.abort(); return;
    }
    await route.continue();
  });
  const beforeCopy = await (await page.request.get("/api/storage/usage")).json();
  await templateCard.getByRole("button", { name: "Використати шаблон", exact: true }).click();
  await templateCard.getByRole("textbox", { name: "Назва нового документа", exact: true }).fill(copyTitle);
  await templateCard.getByRole("button", { name: "Створити та відкрити документ", exact: true }).click();
  await expect(templateCard.getByRole("alert")).toBeVisible();
  await expect(templateCard.getByRole("textbox")).toHaveValue(copyTitle);
  await page.screenshot({ path: testInfo.outputPath("template-copy-retry-uk.png"), fullPage: true });
  await templateCard.getByRole("button", { name: "Створити та відкрити документ", exact: true }).click();
  await expect(page.getByRole("heading", { name: copyTitle, exact: true })).toBeVisible();
  const copyId = page.url().split("/").pop();
  expect(copyKeys[0]).toBe(copyKeys[1]);
  const copyFields = await (await page.request.get(`/api/documents/${copyId}/fields`)).json();
  expect(copyFields.status).toBe("succeeded");
  expect(copyFields.snapshot.candidates).toHaveLength(23);
  const afterCopy = await (await page.request.get("/api/storage/usage")).json();
  expect(afterCopy.used_bytes).toBe(beforeCopy.used_bytes + bytes.length);
  await expect(page.getByRole("textbox", { name: "Редагований документ", exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("template-copy-workspace-uk.png"), fullPage: true });
  await page.getByRole("link", { name: "Бібліотека документів", exact: true }).click();
  await page.getByRole("tab", { name: "Шаблони", exact: true }).click();
  await templateCard.getByRole("button", { name: "Видалити", exact: true }).click();
  await page.getByRole("button", { name: "Видалити назавжди", exact: true }).click();
  await expect(templateCard).toHaveCount(0);
  const independentDownload = await page.request.get(`/api/documents/${copyId}/download`);
  expect(independentDownload.ok()).toBeTruthy(); expect(await independentDownload.body()).toEqual(bytes);
  expect(await (await page.request.get(`/api/documents/${copyId}/fields`)).json()).toEqual(copyFields);
  await page.getByRole("tab", { name: "Документи", exact: true }).click();
  const copyCard = page.getByRole("article", { name: copyTitle });
  await copyCard.getByRole("link", { name: "Відкрити", exact: true }).click();
  await expect(page.getByRole("heading", { name: copyTitle, exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Бібліотека документів", exact: true }).click();
  await copyCard.getByRole("button", { name: "Видалити", exact: true }).click();
  await page.getByRole("button", { name: "Видалити назавжди", exact: true }).click();
  await expect(copyCard).toHaveCount(0);
  await page.getByRole("button", { name: "Вийти", exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
});
