import { manualSaving } from "./autosave-setting";
import { readFile } from "node:fs/promises";
import { expect, test } from "@playwright/test";

test("owned worker suggestions support draft review, grouping, undo and locale changes", async ({ page }, testInfo) => {
  const bytes = await readFile("/fixtures/upload.docx");
  const meetingValue = "Кімната 204\nПоверх 2\tҐанок 🙂";
  const title = `Перевірка полів — ${testInfo.project.name}`;
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await page.getByLabel("Логін", { exact: true }).fill("review@example.test");
  await page.getByLabel("Пароль", { exact: true }).fill("Synthetic-browser-Їжак-2026");
  await page.getByRole("button", { name: "Увійти", exact: true }).click();
  await page.getByLabel("Файл DOCX", { exact: true }).setInputFiles({ name: "Перевірка.docx", mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", buffer: bytes });
  await page.getByLabel("Назва документа", { exact: true }).fill(title);
  await page.getByRole("button", { name: "Завантажити та зберегти", exact: true }).click();
  const libraryCard = page.getByRole("article", { name: title, exact: true });
  await expect(libraryCard.getByText("Перевірку завершено", { exact: true })).toBeVisible({ timeout: 30000 });
  const usage = await (await page.request.get("/api/storage/usage")).json();
  let fail = true;
  await page.route("**/api/documents/*/fields", async route => {
    if (fail) { fail = false; await route.abort(); } else await route.continue();
  });
  await libraryCard.getByRole("link", { name: title, exact: true }).click();
  await expect(page.getByRole("textbox", { name: "Редагований документ", exact: true })).toBeVisible();
  await manualSaving(page);
  await page.getByRole("button", { name: "Повторити запит стану", exact: true }).click();
  await page.getByRole("button", { name: "Наступне поле", exact: true }).click();
  await expect(page.getByRole("article", { name: "Розташування поля 1: ПІБ клієнта", exact: true })).toHaveAttribute("aria-current", "true");
  await expect(page.getByRole("button", { name: "Попереднє поле", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Наступне поле", exact: true }).click();
  await expect(page.getByText("Розташування 2 з 5", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Попереднє поле", exact: true }).click();
  await page.getByRole("complementary", { name: "Поля документа", exact: true }).screenshot({ path: testInfo.outputPath("field-values-uk.png") });
  await page.getByText("Перевірка полів", { exact: true }).click();
  await expect(page.getByText("Відкрито збережену версію.", { exact: true })).toBeVisible();
  const identity = page.url().split("/").at(-1)!;
  const email = page.getByRole("article", { name: "Пропозиція поля: ЕЛЕКТРОННА_ПОШТА", exact: true }).first();
  await email.getByLabel("Назва поля", { exact: true }).fill("Пошта для зв’язку");
  await email.getByRole("combobox", { name: "Пов’язати значення з", exact: true }).selectOption("");
  await email.getByRole("button", { name: "Прийняти", exact: true }).click();
  const mail = page.getByRole("textbox", { name: "Значення поля: Пошта для зв’язку", exact: true });
  await expect(mail).toHaveValue("{{ЕЛЕКТРОННА_ПОШТА}}");
  await mail.fill("їжак@example.test");
  await page.getByRole("button", { name: "Наступні пропозиції", exact: true }).click();
  await page.getByRole("article", { name: "Пропозиція поля: НЕ_ЗАПОВНЮВАТИ", exact: true }).getByRole("button", { name: "Відхилити", exact: true }).click();
  const empty = page.getByRole("article", { name: "Пропозиція поля: Місце зустрічі", exact: true });
  await empty.getByRole("button", { name: "Прийняти", exact: true }).click();
  const meeting = page.getByRole("textbox", { name: "Значення поля: Місце зустрічі", exact: true });
  await expect(meeting).toHaveValue(""); await meeting.fill(meetingValue);
  await page.getByRole("button", { name: "Скасувати", exact: true }).click();
  await expect(meeting).toHaveValue("");
  await page.getByRole("button", { name: "Скасувати", exact: true }).click();
  await expect(meeting).toHaveCount(0);
  await page.getByRole("button", { name: "Повторити", exact: true }).click();
  await page.getByRole("button", { name: "Повторити", exact: true }).click();
  await expect(meeting).toHaveValue(meetingValue);
  await page.getByText("Перевірка полів", { exact: true }).click();
  await page.getByRole("article", { name: /Розташування поля \d+: Місце зустрічі/ }).screenshot({ path: testInfo.outputPath("meeting-field-uk.png") });
  await page.getByText("Перевірка полів", { exact: true }).click();
  await page.getByRole("combobox", { name: "Показати", exact: true }).selectOption("accepted");
  const native = page.getByRole("article", { name: "Пропозиція поля: ПІБ клієнта", exact: true }).first();
  const original = await page.getByRole("textbox", { name: "Значення поля: ПІБ клієнта", exact: true }).first().inputValue();
  await native.getByLabel("Назва поля", { exact: true }).fill("Контактна особа");
  const group = native.getByRole("combobox", { name: "Пов’язати значення з", exact: true });
  const target = await group.getByRole("option", { name: /Пошта для зв’язку/ }).getAttribute("value");
  await group.selectOption(target!);
  await native.getByRole("button", { name: "Застосувати налаштування", exact: true }).click();
  await expect(page.getByRole("textbox", { name: "Значення поля: Контактна особа", exact: true })).toHaveValue(original);
  await expect(mail).toHaveValue("їжак@example.test");
  const renamed = page.getByRole("article", { name: "Пропозиція поля: Контактна особа", exact: true });
  await renamed.getByLabel("Назва поля", { exact: true }).fill("Незастосована назва");
  const sidebar = page.getByRole("complementary", { name: "Поля документа", exact: true });
  await sidebar.evaluate(element => { element.scrollTop = 0; });
  await sidebar.screenshot({ path: testInfo.outputPath("review-uk.png") });
  await page.screenshot({ path: testInfo.outputPath("workspace-review-uk.png") });
  await page.getByRole("link", { name: "Профіль", exact: true }).click();
  await page.getByRole("combobox", { name: "Мова інтерфейсу" }).selectOption("en");
  await page.getByRole("button", { name: "Зберегти мову" }).click();
  await expect(page.getByText("Your language preference has been saved.", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Document workspace", exact: true }).click();
  await expect(page.getByRole("article", { name: "Field suggestion: Контактна особа", exact: true }).getByLabel("Field label", { exact: true })).toHaveValue("Незастосована назва");
  await expect(page.getByRole("textbox", { name: "Field value: Місце зустрічі", exact: true })).toHaveValue(meetingValue);
  await page.getByRole("complementary", { name: "Document fields", exact: true }).screenshot({ path: testInfo.outputPath("review-en.png") });
  await page.getByText("Review fields", { exact: true }).click();
  await page.getByRole("button", { name: "Go to field: Контактна особа", exact: true }).click();
  await expect(page.getByText("Location 1 of 7", { exact: true })).toBeVisible();
  await page.getByRole("complementary", { name: "Document fields", exact: true }).screenshot({ path: testInfo.outputPath("field-values-en.png") });
  await page.getByRole("article", { name: /Field location \d+: Місце зустрічі/ }).screenshot({ path: testInfo.outputPath("meeting-field-en.png") });
  const after = await (await page.request.get("/api/storage/usage")).json();
  expect(after.used_bytes).toBe(usage.used_bytes); expect(after.reserved_bytes).toBe(usage.reserved_bytes);
  expect(await (await page.request.get(`/api/documents/${identity}/download`)).body()).toEqual(bytes);
  const persisted = await (await page.request.get(`/api/documents/${identity}/fields`)).json();
  expect(persisted.snapshot.decisions).toHaveLength(5); // Working review persistence is E06.
  await page.getByRole("link", { name: "Profile", exact: true }).click();
  await page.getByRole("combobox", { name: "Interface language" }).selectOption("uk");
  await page.getByRole("button", { name: "Save language" }).click();
  await expect(page.getByText("Мову інтерфейсу збережено.", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Бібліотека документів", exact: true }).click();
  await libraryCard.getByRole("button", { name: "Видалити", exact: true }).click();
  await page.getByRole("button", { name: "Видалити назавжди", exact: true }).click();
  await expect(libraryCard).toHaveCount(0);
  page.once("dialog", dialog => dialog.accept());
  await page.getByRole("button", { name: "Вийти", exact: true }).click();
  await expect(page.getByRole("button", { name: "Увійти", exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
